name       : xmlto
version    : 0.0.28
release    : 4
source     :
    - https://releases.pagure.org/xmlto/xmlto-0.0.28.tar.bz2 : 1130df3a7957eb9f6f0d29e4aa1c75732a7dfb6d639be013859b5c7ec5421276
license    : GPL-2.0-or-later
component  : system.utils
summary    : Convert XML to various formats
builddeps  :
    - pkgconfig(libxslt)
description: |
    xmlto converts XML files to various formats, and at the moment it supports conversion from docbook, xhtml1 and fo format to various output formats (awt, fo, htmlhelp, javahelp, mif, pdf, svg, xhtml, dvi, html, html-nochunks, man , pcl, ps, txt, xhtml-nochunks, epub).
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
