name        : xmlto
version     : 0.0.26
release     : 3
source     :
    - https://fedorahosted.org/releases/x/m/xmlto/xmlto-0.0.26.tar.bz2 : efb49b2fb3bc27c1a1e24fe34abf19b6bf6cbb40844e6fd58034cdf21c54b5ec
license     :
    - GPLv2
summary     : Convert XML to various formats
builddeps   :
    - libxml2-devel
    - libxslt-devel
    - zip
description : |
    xmlto converts XML files to various formats, and at the moment it supports conversion from docbook, xhtml1 and fo format to various output formats (awt, fo, htmlhelp, javahelp, mif, pdf, svg, xhtml, dvi, html, html-nochunks, man , pcl, ps, txt, xhtml-nochunks, epub).
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
